"""empty message

Revision ID: 11af0af6d6b0
Revises: 2d203a4694c7
Create Date: 2017-12-05 10:19:57.363026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11af0af6d6b0'
down_revision = '2d203a4694c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'upvote_user_ibfk_2', 'upvote_user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'upvote_user_ibfk_2', 'upvote_user', 'user', ['user2_id'], ['id'])
    # ### end Alembic commands ###
