"""empty message

Revision ID: 15a496239ca0
Revises: af1e5421d962
Create Date: 2017-12-07 00:51:45.399847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a496239ca0'
down_revision = 'af1e5421d962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('test', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'test')
    # ### end Alembic commands ###
