"""empty message

Revision ID: 695821e924b5
Revises: 
Create Date: 2017-12-03 18:29:23.718759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '695821e924b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'food_ibfk_1', 'food', type_='foreignkey')
    op.drop_column('food', 'step_id')
    op.add_column('step', sa.Column('food_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step', 'food', ['food_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'food_id')
    op.add_column('food', sa.Column('step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'food_ibfk_1', 'food', 'step', ['step_id'], ['id'])
    # ### end Alembic commands ###
