"""empty message

Revision ID: bf7f479b0a76
Revises: 11af0af6d6b0
Create Date: 2017-12-05 23:03:29.198666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf7f479b0a76'
down_revision = '11af0af6d6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvote_user')
    op.drop_column('upvote', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvote', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_table('upvote_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user1_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], [u'user.id'], name=u'upvote_user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
