"""empty message

Revision ID: fd36c7b3af50
Revises: 9ed9bb995c44
Create Date: 2017-12-07 00:52:39.153410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd36c7b3af50'
down_revision = '9ed9bb995c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('desc', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'desc')
    # ### end Alembic commands ###
